/* Generate library3.js — the read-only dataset behind Font Lab 3.
   Everything the tool needs is baked in: the spec that shipped, and which of the
   four built cuts exist for each family, so variant resolution never has to probe
   the filesystem at runtime. */
const fs = require('fs'), path = require('path');
const HERE = __dirname, ROOT = path.dirname(HERE);
global.window = {};
require(path.join(ROOT, 'library.js'));
const META = Object.fromEntries(window.FL2_FONTS.map(f => [f.n, f]));
const D = JSON.parse(fs.readFileSync(path.join(ROOT, 'display-specs-2026-08-31.json'), 'utf8'));
const MAN = JSON.parse(fs.readFileSync(path.join(ROOT, 'built-fonts', 'manifest.json'), 'utf8'));

const byFam = {};
for (const c of MAN.cuts) {
  const k = c.source;
  (byFam[k] = byFam[k] || {})[(c.cut === 'caps' ? 'caps' : 'roman') + (c.style === 'Italic' ? 'Italic' : '')] =
    { file: c.file, family: c.family, kind: c.kind };
}
const fonts = Object.entries(D.specs).map(([src, sp]) => {
  const m = META[src] || {}, cuts = byFam[src] || {};
  return {
    n: src,
    token: sp.name || src,
    cat: m.cat || 'Display',
    lane: m.lane || '',
    origin: m.src || '',
    weight: sp.weight,
    ls: sp.ls,
    caps: sp.caps,
    nudge: sp.nudge || 0,
    needsMetrics: !!sp.needsMetrics,
    note: sp.metricsNote || '',
    sizes: sp.sizes,
    /* roman / romanItalic / caps / capsItalic — absent keys mean that cut was never
       built, which is what the global switcher falls back from. */
    cuts,
  };
});
fonts.sort((a, b) => a.token.localeCompare(b.token));
const out =
  '// Font Lab 3 data — generated by _build/make_library3.js from the spec export\n' +
  '// and built-fonts/manifest.json. Read-only: Font Lab 3 browses what shipped.\n' +
  'window.FL3_LH = ' + JSON.stringify(D.lineHeights) + ';\n' +
  'window.FL3_FONTS = ' + JSON.stringify(fonts) + ';\n';
fs.writeFileSync(path.join(ROOT, 'library3.js'), out);
const n = k => fonts.filter(f => f.cuts[k]).length;
console.log('families', fonts.length, '| roman', n('roman'), 'romanItalic', n('romanItalic'),
            '| caps', n('caps'), 'capsItalic', n('capsItalic'), '| bytes', out.length);
