#!/usr/bin/env python3
"""Parse the Font Match Research markdown into matches.js for Font Lab 3.

The markdown carries three tables that overlap heavily: 145 custom families, 47
clusters, and a 663-family inventory of every liked Google font. The prose columns
(why it matches, what differs, the Adobe and paid options) are properties of the
CLUSTER, repeated on every row that belongs to it — so the parser keeps them once on
the cluster and stores only what is genuinely per family. That is the difference
between a ~150KB payload and a ~600KB one.
"""
import io, json, re, sys, os

SRC = sys.argv[1]
OUT = sys.argv[2]
SPECS = sys.argv[3]

md = io.open(SRC, encoding='utf8').read()
lines = md.split('\n')

LINK = re.compile(r'\[([^\]]+)\]\(([^)]+)\)')
def plain(s):
    """Markdown cell → text, with any links pulled out separately."""
    urls = LINK.findall(s or '')
    txt = LINK.sub(r'\1', s or '').replace('·', '·').strip()
    return txt, [{'label': a, 'url': b} for a, b in urls]

def table(startswith):
    i = next(i for i, l in enumerate(lines) if l.startswith(startswith))
    hdr = [c.strip() for c in lines[i].strip().strip('|').split('|')]
    rows, i = [], i + 2
    while i < len(lines) and lines[i].startswith('|'):
        cells = [c.strip() for c in lines[i].strip().strip('|').split('|')]
        if len(cells) == len(hdr): rows.append(dict(zip(hdr, cells)))
        i += 1
    return rows

# ── clusters ────────────────────────────────────────────────────────────────
clusters = {}
for i, l in enumerate(lines):
    m = re.match(r'^### ([A-Z]\d{2}) — (.+)$', l)
    if not m: continue
    cid, name = m.group(1), m.group(2)
    d, j = {}, i + 1
    while j < len(lines) and not lines[j].startswith('###') and not lines[j].startswith('## '):
        mm = re.match(r'^- \*\*(.+?):\*\*\s*(.*)$', lines[j])
        if mm: d[mm.group(1)] = mm.group(2)
        j += 1
    adobe, _ = plain(d.get('Closest Adobe Fonts option', ''))
    paid, _ = plain(d.get('Other paid option', ''))
    src, links = plain(d.get('Sources', ''))
    members = [x.strip() for x in d.get('Liked families represented', '').split(';') if x.strip()]
    clusters[cid] = {
        'id': cid, 'name': name,
        'genre': d.get('Genre', ''),
        'adobe': adobe, 'paid': paid,
        'confidence': d.get('Confidence', ''),
        'score': d.get('Upgrade score', ''),
        'why': plain(d.get('Why it matches', ''))[0],
        'differs': plain(d.get('What differs', ''))[0],
        'members': members,
        'links': links,
    }

# ── the 145 custom families ─────────────────────────────────────────────────
custom = {}
for r in table('| Custom family |'):
    cid = r['Match cluster'].split(' — ')[0].strip()
    setup, _ = plain(r['Paid comparison setup'])
    custom[r['Custom family']] = {
        'source': r['Based on'],
        'cluster': cid,
        'confidence': r['Confidence'],
        'setup': setup,

    }
    for key, col in (('adobe', 'Closest Adobe Fonts option'), ('paid', 'Other paid option'),
                     ('why', 'Why it matches'), ('differs', 'Key difference / caveat')):
        val, _ = plain(r[col])
        if cid in clusters and val and val != clusters[cid].get(key):
            custom[r['Custom family']][key] = val

# ── the 663-family liked inventory ──────────────────────────────────────────
families = {}
for r in table('| Family | Google category |'):
    cid = r['Cluster ID'].strip()
    e = {'cluster': cid, 'cat': r['Google category'], 'script': r['Primary script'],
         'designer': plain(r['Designer(s)'])[0], 'confidence': r['Confidence']}
    for key, col in (('adobe', 'Closest Adobe Fonts option'), ('paid', 'Other paid option'),
                     ('why', 'Why it matches'), ('differs', 'Key difference / caveat')):
        val, _ = plain(r[col])
        if cid in clusters and val and val != clusters[cid].get(key):
            e[key] = val
    families[r['Family']] = e

specs = json.load(open(SPECS))['specs']
tokens = {(v['name'] or k): k for k, v in specs.items()}
inlib = {k: v for k, v in tokens.items()}

payload = {'generated': '2026-08-31', 'source': os.path.basename(SRC),
           'clusters': clusters, 'custom': custom, 'families': families}
out = ('// Font Lab 3 match data — generated by _build/make_matches.py from\n'
       '// ' + os.path.basename(SRC) + '. Cluster prose is stored once; families carry only\n'
       '// what actually differs from their cluster.\n'
       'window.FL3_MATCH = ' + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ';\n')
io.open(OUT, 'w', encoding='utf8').write(out)

miss = [t for t in tokens if t not in custom]
overrides = sum(1 for v in list(custom.values()) + list(families.values())
                if any(k in v for k in ('adobe', 'paid', 'why', 'differs')))
print('clusters', len(clusters), '| custom', len(custom), '| families', len(families))
print('token names missing from the custom table:', miss)
print('rows needing a per-family override:', overrides)
print('bytes', len(out))
