#!/usr/bin/env python3
"""
build-fonts.py — turn the Font Lab build output into the shipped web font layer.

Input   tools/font-lab/built-fonts/   (.ttf cuts + manifest.json)
        tools/font-lab/display-specs.json
Output  fonts/*.woff2                 one default cut per family
        fonts/catalog.json            machine-readable family list
        css/fonts.css                 @font-face per family
        css/display-fonts.css         [data-display-font] token bundles

Run:    python3 scripts/build-fonts.py
Needs:  pip install fonttools brotli
"""
import json, os, re, sys
from fontTools.ttLib import TTFont

ROOT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILT = os.path.join(ROOT, 'tools/font-lab/built-fonts')
SPECS = os.path.join(ROOT, 'tools/font-lab/display-specs.json')
FONTS = os.path.join(ROOT, 'fonts')
CSS   = os.path.join(ROOT, 'css')

slug = lambda n: re.sub(r'[^a-z0-9]+', '-', n.lower()).strip('-')

def main():
    cuts  = json.load(open(f'{BUILT}/manifest.json'))['cuts']
    specs = json.load(open(SPECS))['specs']            # keyed by source family
    lhs   = json.load(open(SPECS))['lineHeights']

    # the cut that ships per family: the caps cut where the spec says caps
    ship = [c for c in cuts
            if c['style'] == 'Regular' and (c['caseMode'] == 'caps') == (c['cut'] == 'caps')]
    ship.sort(key=lambda c: c['family'])

    os.makedirs(FONTS, exist_ok=True)
    faces, families, total = [], [], 0

    for c in ship:
        spec = specs.get(c['source'], {})
        token = spec.get('name') or re.sub(r' Caps$', '', c['family'])
        key   = slug(token)
        fname = f'{key}.woff2'

        f = TTFont(f"{BUILT}/{c['file']}")
        f.flavor = 'woff2'
        f.save(f'{FONTS}/{fname}')
        size = os.path.getsize(f'{FONTS}/{fname}')
        total += size

        faces.append((c['family'], fname, c['weight'], c['source'], c['license']))
        families.append({
            'key': key, 'name': token, 'fontFamily': c['family'], 'file': fname,
            'source': c['source'], 'license': c['license'],
            'weight': c['weight'], 'letterSpacing': spec.get('ls', c['letterSpacing']),
            'caps': c['cut'] == 'caps',
            'sizes': spec.get('sizes', {}), 'bytes': size,
        })

    json.dump({'count': len(families), 'bytes': total, 'lineHeights': lhs,
               'families': families}, open(f'{FONTS}/catalog.json', 'w'), indent=1)

    # ── css/fonts.css ────────────────────────────────────────────────────────
    out = io_header('fonts.css',
      'Every shipped display face, plus the UI face.',
      ['- One @font-face per display family, served from fonts/',
       '- Families are OFL / Apache cuts of open fonts, renamed and re-metricated;',
       '  the source family and licence for each is in fonts/catalog.json and the',
       '  full licence text in fonts/licenses/',
       '- A `Caps` family remaps lowercase codepoints to the uppercase glyphs, so',
       '  title-case copy renders as caps with uppercase kerning intact'],
      ['- Declaring a face does not download it. The browser fetches only the one',
       '  the active theme names in --display-font.',
       '- Inter (the UI face) comes from the Google Fonts <link> in the page head.',
       '- Which face a theme uses is bound through --display-font, not here.'])
    for family, fname, weight, source, lic in faces:
        out.append(f"/* {family} — from {source} ({lic.upper()}) */")
        out.append('@font-face {')
        out.append(f"  font-family: '{family}';")
        out.append(f"  src: url('../fonts/{fname}') format('woff2');")
        out.append(f'  font-weight: {weight};')
        out.append('  font-style: normal;')
        out.append('  font-display: swap;')
        out.append('}')
        out.append('')
    open(f'{CSS}/fonts.css', 'w').write('\n'.join(out))

    # ── css/display-fonts.css ────────────────────────────────────────────────
    steps = ['900','800','700','600','500','400','300','200','100']
    out = io_header('display-fonts.css',
      'A ready-tuned display ramp for each shipped face.',
      ['- One [data-display-font="key"] block per family, setting --display-font,',
       '  --display-weight, --display-letter-spacing and the nine --display-size-*'],
      ['- Set it on <html> beside data-theme to swap the display face without',
       '  touching the theme:  <html data-theme="slate" data-display-font="gantry">',
       '- Or copy a block\'s values into a theme so the face travels with it.',
       '- Line heights are fixed system-wide (76/68/60/52/44/36/28/24/20) and live',
       '  in text-styles-system.css. A size above its line height is clipped on iOS.',
       '- Generated by scripts/build-fonts.py — do not hand-edit.'])
    for fam in families:
        sizes = fam['sizes']
        if not sizes: continue
        caps = ' · renders caps' if fam['caps'] else ''
        out.append(f"/* {fam['name']} — {fam['source']} ({fam['license'].upper()}){caps} */")
        out.append(f"[data-display-font=\"{fam['key']}\"] {{")
        out.append(f"  --display-font: '{fam['fontFamily']}', 'Inter', system-ui, sans-serif;")
        out.append(f"  --display-weight: {fam['weight']};")
        out.append(f"  --display-letter-spacing: {fam['letterSpacing']}em;")
        for s in steps:
            if s in sizes: out.append(f'  --display-size-{s}: {sizes[s]}px;')
        out.append('}')
        out.append('')
    open(f'{CSS}/display-fonts.css', 'w').write('\n'.join(out))

    print(f'{len(families)} families · {total/1e6:.1f} MB woff2 · fonts.css + display-fonts.css written')

def io_header(name, summary, inside, notes):
    L = ['/* ============================================================',
         f'   {name}',
         '   ============================================================',
         f'   {summary}', '', "   What's inside"]
    L += ['   ' + l for l in inside]
    L += ['', '   Notes'] + ['   ' + l for l in notes]
    L += ['   ============================================================ */', '']
    return L

if __name__ == '__main__':
    main()
